services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    # entrypoint: "caddy run"
    environment:
      - CADDY_ENV=test-caddy-value
      - ADMIN_PORT=2019
      - SERVE_PORT=80
      - RESPONSE_TEXT=HELLO ENV
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
